name = "Alabaster 2"
license = "BSD"
licenselink = "https://github.com/NickolasHKraus/alabaster-2/blob/master/LICENSE"
description = "A simple documentation theme for Hugo. Alabaster 2 is a port of Sphinx to Hugo, JavaScript-free, and fully open-source."
homepage = "https://github.com/NickolasHKraus/alabaster-2"
tags = []
features = []
min_version = 0.55.4

[author]
  name = "Nickolas Kraus"
  homepage = "https://github.com/NickolasHKraus"
  repo = "https://github.com/NickolasHKraus/alabaster-2"

[original]
  name = "Digitalcraftsman"
  homepage = "https://github.com/digitalcraftsman"
  repo = "https://github.com/digitalcraftsman/hugo-alabaster-theme"

[original]
  name = "Jeff Forcier"
  homepage = "https://github.com/bitprophet"
  repo = "https://github.com/bitprophet/alabaster"
