name = "Alabaster 2"
license = "MIT"
licenselink = "https://github.com/NickolasHKraus/alabaster-2/blob/master/LICENSE"
description = "A simple, documentation theme for Hugo. Alabaster 2 is JavaScript-free and fully open-source!"
homepage = "https://github.com/NickolasHKraus/alabaster-2"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Nickolas Kraus"
  homepage = "https://nickolaskraus.org"

[original]
  name = "Digitalcraftsman"
  homepage = "https://github.com/digitalcraftsman"
  repo = "https://github.com/digitalcraftsman/hugo-alabaster-theme"
